[project]
name = "vidownload"
version = "0.1.0"
description = "API para extraer formatos de video y audio usando FastAPI y yt-dlp"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.100.0",
    "uvicorn>=0.20.0",
    "python-multipart>=0.0.5",
    "python-dotenv>=1.0.0",
    "yt-dlp>=2025.0.0", # Forzar versiones modernas y estables
]
